# TODO: Update this file
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['USERNAME', 'PASSWORD']

  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--target', 'slim',
      '-t', 'joelwalshwest/fastapi-scaffolding:$COMMIT_SHA',
      '.',
      '--platform=linux/amd64',
      '--no-cache'
    ]

  # Step 2: Push the Docker image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'docker.io/joelwalshwest/fastapi-scaffolding:$COMMIT_SHA'
    ]

  # Step 3: Deploy to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'fastapi-scaffolding',
      '--image', 'docker.io/joelwalshwest/fastapi-scaffolding:$COMMIT_SHA',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--region', 'us-east1'
    ]
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
   secretManager:
   - versionName: projects/fastapi-scaffolding/secrets/DOCKER_PASSWORD/versions/latest
     env: 'PASSWORD'
   - versionName: projects/fastapi-scaffolding/secrets/DOCKER_USERNAME/versions/latest
     env: 'USERNAME'
