name: test-praxis-server

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/praxis_server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/praxis_server/**'


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test
      env:
        ENVIRONMENT: local
      run: |
        python3 -m unittest discover .
